name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      
      - name: Run Ansible Playbook
        run: ansible-playbook deploy.yml --extra-vars "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" --extra-vars "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"
